# Wordpress image for Testops Factory
services:
  wordpress_testopsfactory:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:80"
    env_file:
      - ../.env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_volume_testopsfactory:/var/www/html

volumes:
  wordpress_volume_testopsfactory:
